name: toefl
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  easy_localization: ^3.0.6
  flutter_svg: ^2.0.10+1
  just_audio: ^0.9.37
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  skeletonizer: ^1.1.2+1
  easy_debounce: ^2.0.3
  flutter_widget_from_html: ^0.15.0
  slide_countdown: ^1.6.1
  lottie: ^3.1.1
  riverpod_annotation: ^2.3.5
  mockito: ^5.4.4
  equatable: ^2.0.5
  flutter_otp_text_field: ^1.1.3+2
  restart_app: ^1.2.1
  smooth_page_indicator: ^1.1.0
  local_auth: ^2.2.0
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  permission_handler: ^11.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - assets/icons/
    - assets/images/
    - assets/json/
